kind: Service
apiVersion: v1
metadata:
  name: sender
  namespace: karen-dev
spec:
  selector:
    app: senderapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
