apiVersion: v1
kind: ConfigMap
metadata:
  name: configapp
  namespace: karen-dev
data:
  URL_BROKER: "failover:(tcp://activemq:61616)"
  QUEUENAME: "mailbox"
  JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n -Xms256m -Xmx512m -XX:MaxMetaspaceSize=128m"
  #JAVA_OPTS: "--enable-preview  -XX:MaxRAMPercentage=80 -XX:+UseG1GC"
